import {
  Component
} from '@angular/core';

import {
  NavController,
  NavParams
} from 'ionic-angular';

import {
  ClubDetails
} from '../ClubDetails/ClubDetails';

const clubList = [{
  league: {
    id: 'Premier League',
    country: 'England',
    teams: [{
      name: 'Arsenal',
      stadium: 'Emirates Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 60361,
      badge: 'assets/imgs/england/premierLeague/arsenal.png',
      sponsor: 'emirates.png',
      rival: 'Tottenham Hotspurs',
      founded: 1886,
      opened: 2006,
      hashTag: '#Arsenal',
      knownAs: 'The Gunners',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bournemouth',
      stadium: 'Vitality Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 11464,
      badge: 'assets/imgs/england/premierLeague/bournmouth.png',
      sponsor: 'vitality.png',
      rival: 'Southampton',
      founded: 1890,
      opened: 1910,
      hashTag: '#AFCB',
      knownAs: 'The Cherries',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Brighton and Hove Albion',
      stadium: 'Amex Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 22374,
      badge: 'assets/imgs/england/premierLeague/brighton.png',
      sponsor: 'amex.png',
      rival: 'Crystal Palace',
      founded: 1901,
      opened: 2011,
      hashTag: '#BHAFC',
      knownAs: 'The Seagulls',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Burnley',
      stadium: 'Turf Moor',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 22546,
      badge: 'assets/imgs/england/premierLeague/burnley.png',
      sponsor: 'BLANK.png',
      rival: 'Blackburn Rovers',
      founded: 1882,
      opened: 1883,
      hashTag: '#BFC',
      knownAs: 'The Clarets',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Chelsea',
      stadium: 'Stamford Bridge',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 41837,
      badge: 'assets/imgs/england/premierLeague/chelsea.png',
      sponsor: 'BLANK.png',
      rival: 'Fulham',
      founded: 1905,
      opened: 1905,
      hashTag: '#CFC',
      knownAs: 'The Blues',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Crystal Palace',
      stadium: 'Selhurst Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 26309,
      badge: 'assets/imgs/england/premierLeague/crystalPalace.png',
      sponsor: 'BLANK.png',
      rival: 'Charlton Athletic',
      founded: 1905,
      opened: 1924,
      hashTag: '#CPFC',
      knownAs: 'The Eagles',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Everton',
      stadium: 'Goodison Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 40157,
      badge: 'assets/imgs/england/premierLeague/everton.png',
      sponsor: 'BLANK.png',
      rival: 'Liverpool',
      founded: 1878,
      opened: 1892,
      hashTag: '#EFC',
      knownAs: 'The Toffees',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Huddersfield Town',
      stadium: 'The John Smith\'s Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 24500,
      badge: 'assets/imgs/england/premierLeague/huddersfield.png',
      sponsor: 'johnsmith.png',
      rival: 'Leeds United',
      founded: 1908,
      opened: 1994,
      hashTag: '#HTAFC',
      knownAs: 'The Terriers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Leicester City',
      stadium: 'King Power Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 32262,
      badge: 'assets/imgs/england/premierLeague/leicester.png',
      sponsor: 'kingPower.png',
      rival: 'Derby County',
      founded: 1884,
      opened: 2002,
      hashTag: '#LCFC',
      knownAs: 'The Foxes',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Liverpool',
      stadium: 'Anfield',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 45522,
      badge: 'assets/imgs/england/premierLeague/liverpool.png',
      sponsor: 'BLANK.png',
      rival: 'Everton',
      founded: 1892,
      opened: 1884,
      hashTag: '#LFC',
      knownAs: 'The Reds',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Manchester City',
      stadium: 'Etihad Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 47805,
      badge: 'assets/imgs/england/premierLeague/manchesterCity.png',
      sponsor: 'etihad.png',
      rival: 'Manchester United',
      founded: 1880,
      opened: 2002,
      hashTag: '#MCFC',
      knownAs: 'The Citizens',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Manchester United',
      stadium: 'Old Trafford',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 75811,
      badge: 'assets/imgs/england/premierLeague/manchesterUnited.png',
      sponsor: 'BLANK.png',
      rival: 'Manchester City',
      founded: 1878,
      opened: 1910,
      hashTag: '#MUFC',
      knownAs: 'The Red Devils',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Newcastle United',
      stadium: 'St James\' Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 52387,
      badge: 'assets/imgs/england/premierLeague/newcastle.png',
      sponsor: 'BLANK.png',
      rival: 'Sunderland',
      founded: 1892,
      opened: 1892,
      hashTag: '#NUFC',
      knownAs: 'The Magpies',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Southampton',
      stadium: 'St Mary\'s Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 32689,
      badge: 'assets/imgs/england/premierLeague/southampton.png',
      sponsor: 'BLANK.png',
      rival: 'Portsmouth',
      founded: 1885,
      opened: 2001,
      hashTag: '#SaintsFC',
      knownAs: 'The Saints',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Stoke City',
      stadium: 'Britannia Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 27598,
      badge: 'assets/imgs/england/premierLeague/stoke.png',
      sponsor: 'britannia.png',
      rival: 'Port Vale',
      founded: 1863,
      opened: 1997,
      hashTag: '#SCFC',
      knownAs: 'The Potters',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Swansea City',
      stadium: 'Liberty Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 20532,
      badge: 'assets/imgs/england/premierLeague/swansea.png',
      sponsor: 'liberty.png',
      rival: 'Cardiff City',
      founded: 1912,
      opened: 2005,
      hashTag: '#Swans',
      knownAs: 'The Swans',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Tottenham Hotspur',
      stadium: 'White Hart Lane',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 36230,
      badge: 'assets/imgs/england/premierLeague/tottenham.png',
      sponsor: 'BLANK.png',
      rival: 'Arsenal',
      founded: 1882,
      opened: 1899,
      hashTag: '#COYS',
      knownAs: 'Spurs',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Watford',
      stadium: 'Vicarage Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 17477,
      badge: 'assets/imgs/england/premierLeague/watford.png',
      sponsor: 'BLANK.png',
      rival: 'Luton Town',
      founded: 1881,
      opened: 1922,
      hashTag: '#WatfordFC',
      knownAs: 'The Hornets',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'West Bromwich Albion',
      stadium: 'The Hawthorns',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 26272,
      badge: 'assets/imgs/england/premierLeague/wba.png',
      sponsor: 'BLANK.png',
      rival: 'Wolverhampton Wanderers',
      founded: 1878,
      opened: 1900,
      hashTag: '#WBA',
      knownAs: 'The Baggies',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'West Ham United',
      stadium: 'Boleyn Ground',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 35016,
      badge: 'assets/imgs/england/premierLeague/westHam.png',
      sponsor: 'BLANK.png',
      rival: 'Millwall',
      founded: 1895,
      opened: 1904,
      hashTag: '#WHUFC',
      knownAs: 'The Hammers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }]
  }
},
{
  league: {
    id: 'Championship',
    country: 'England',
    teams: [{
      name: 'Aston Villa',
      stadium: 'Villa Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 42788,
      badge: 'assets/imgs/england/championship/astonVilla.png',
      sponsor: 'BLANK.png',
      rival: 'Birmingham City',
      founded: 1874,
      opened: 1897,
      hashTag: '#AVFC',
      knownAs: 'The Villans',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Birmingham City',
      stadium: 'St Andrews',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 30009,
      badge: 'assets/imgs/england/championship/barnsley.png',
      sponsor: 'BLANK.png',
      rival: 'Aston Villa',
      founded: 1875,
      opened: 1906,
      hashTag: '#BCFC',
      knownAs: 'The Blues',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Barnsley',
      stadium: 'Oakwell',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 23009,
      badge: 'assets/imgs/england/championship/birmingham.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'Leeds United?',
      founded: 1887,
      opened: 1888,
      hashTag: '#BarnsleyFC',
      knownAs: 'The Tykes',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bolton Wanderers',
      stadium: 'Macron Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 28723,
      badge: 'assets/imgs/england/championship/bolton.png',
      sponsor: 'macron.png',
      rival: 'Wigan Athletic',
      founded: 1874,
      opened: 1997,
      hashTag: '#BWFC',
      knownAs: 'The Trotters',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Brentford',
      stadium: 'Griffin Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 12763,
      badge: 'assets/imgs/england/championship/brentford.png',
      sponsor: 'BLANK.png',
      rival: 'Queens Park Rangers',
      founded: 1889,
      opened: 1904,
      hashTag: '#BrentfordFC',
      knownAs: 'The Bees',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bristol City',
      stadium: 'Ashton Gate',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 21497,
      badge: 'assets/imgs/england/championship/bristolCity.png',
      sponsor: 'BLANK.png',
      rival: 'Bristol Rovers',
      founded: 1897,
      opened: 1904,
      hashTag: '#BristolCity',
      knownAs: 'The Robins',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Burton Albion',
      stadium: 'Pirelli Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 6912,
      badge: 'assets/imgs/england/championship/burton.png',
      sponsor: 'BLANK.png',
      rival: 'Derby County',
      founded: 1950,
      opened: 2005,
      hashTag: '#BAFC',
      knownAs: 'The Brewers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Cardiff City',
      stadium: 'Cardiff City Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 26828,
      badge: 'assets/imgs/england/championship/cardiff.png',
      sponsor: 'BLANK.png',
      rival: 'Swansea City',
      founded: 1899,
      opened: 2009,
      hashTag: '#CardiffCity',
      knownAs: 'The Bluebirds',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Derby County',
      stadium: 'Pride Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 33597,
      badge: 'assets/imgs/england/championship/derby.png',
      sponsor: 'BLANK.png',
      rival: 'Leicester City',
      founded: 1884,
      opened: 1997,
      hashTag: '#DCFC',
      knownAs: 'The Rams',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Fulham',
      stadium: 'Craven Cottage',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 25700,
      badge: 'assets/imgs/england/championship/fulham.png',
      sponsor: 'BLANK.png',
      rival: 'Chelsea',
      founded: 1879,
      opened: 1894,
      hashTag: '#FFC',
      knownAs: 'The Cottagers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Hull City',
      stadium: 'KC Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 25586,
      badge: 'assets/imgs/england/championship/hull.png',
      sponsor: 'kc.png',
      rival: 'Leeds United',
      founded: 1904,
      opened: 2002,
      hashTag: '#HCFC',
      knownAs: 'The Tigers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Ipswich Town',
      stadium: 'Portman Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 30311,
      badge: 'assets/imgs/england/championship/ipswich.png',
      sponsor: 'BLANK.png',
      rival: 'Norwich City',
      founded: 1878,
      opened: 1888,
      hashTag: '#ITFC',
      knownAs: 'Tractor Boys',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Leeds United',
      stadium: 'Elland Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 37697,
      badge: 'assets/imgs/england/championship/leeds.png',
      sponsor: 'BLANK.png',
      rival: 'Bradford City',
      founded: 1919,
      opened: 1919,
      hashTag: '#LUFC',
      knownAs: 'United',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Middlesbrough',
      stadium: 'Riverside',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 34988,
      badge: 'assets/imgs/england/championship/middlesbrough.png',
      sponsor: 'BLANK.png',
      rival: 'Newcastle, Sunderland',
      founded: 1876,
      opened: 1995,
      hashTag: '#Boro',
      knownAs: 'Boro',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Millwall',
      stadium: 'The Den',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 20146,
      badge: 'assets/imgs/england/championship/millwall.png',
      sponsor: 'BLANK.png',
      rival: 'West Ham United',
      founded: 1885,
      opened: 1993,
      hashTag: '#Millwall',
      knownAs: 'Lions',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Norwich City',
      stadium: 'Carrow Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 27033,
      badge: 'assets/imgs/england/championship/norwich.png',
      sponsor: 'BLANK.png',
      rival: 'Ipswich Town',
      founded: 1902,
      opened: 1935,
      hashTag: '#NCFC',
      knownAs: 'The Canaries',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Nottingham Forest',
      stadium: 'The City Ground',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 30603,
      badge: 'assets/imgs/england/championship/nottingham.png',
      sponsor: 'BLANK.png',
      rival: 'Notts County',
      founded: 1865,
      opened: 1898,
      hashTag: '#NFFC',
      knownAs: 'The Reds',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Preston North End',
      stadium: 'Deepdale',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 24500,
      badge: 'assets/imgs/england/championship/preston.png',
      sponsor: 'BLANK.png',
      rival: 'Blackpool',
      founded: 1880,
      opened: 1875,
      hashTag: '#PNE',
      knownAs: 'The Lilywhites',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Queens Park Rangers',
      stadium: 'Loftus Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 18360,
      badge: 'assets/imgs/england/championship/qpr.png',
      sponsor: 'BLANK.png',
      rival: 'Brentford',
      founded: 1886,
      opened: 1917,
      hashTag: '#QPR',
      knownAs: 'The Superhoops',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Reading',
      stadium: 'Madjeski Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 24161,
      badge: 'assets/imgs/england/championship/reading.png',
      sponsor: 'BLANK.png',
      rival: 'Swindon Town',
      founded: 1871,
      opened: 1998,
      hashTag: '#ReadingFC',
      knownAs: 'The Royals',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Sheffield United',
      stadium: 'Bramall Lane',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 32702,
      badge: 'assets/imgs/england/championship/sheffieldUnited.png',
      sponsor: 'BLANK.png',
      rival: 'Sheffield Wednesday',
      founded: 1889,
      opened: 1862,
      hashTag: '#SUFC',
      knownAs: 'The Blades',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Sheffield Wednesday',
      stadium: 'Hillsborough',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 39812,
      badge: 'assets/imgs/england/championship/sheffieldWednesday.png',
      sponsor: 'BLANK.png',
      rival: 'Sheffield United',
      founded: 1867,
      opened: 1899,
      hashTag: '#SWFC',
      knownAs: 'The Owls',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Sunderland',
      stadium: 'Stadium of Light',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 49000,
      badge: 'assets/imgs/england/championship/sunderland.png',
      sponsor: 'BLANK.png',
      rival: 'Newcastle United',
      founded: 1879,
      opened: 1997,
      hashTag: '#SAFC',
      knownAs: 'The Black Cats',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Wolverhampton Wanderers',
      stadium: 'Molineux',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 27828,
      badge: 'assets/imgs/england/championship/wolverhampton.png',
      sponsor: 'BLANK.png',
      rival: 'West Bromich Albion',
      founded: 1877,
      opened: 1889,
      hashTag: '#WWFC',
      knownAs: 'Wolves',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }]
  }
},
{
  league: {
    'id': 'League One',
    'country': 'England',
    'teams': [{
      name: 'AFC Wimbledon',
      stadium: 'Kingsmeadow',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 4720,
      badge: 'assets/imgs/england/leagueOne/afcw.png',
      sponsor: 'BLANK.png',
      rival: 'MK Dons',
      founded: 2002,
      opened: 1989,
      hashTag: '#AFCW',
      knownAs: 'The Dons',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Blackburn Rovers',
      stadium: 'Ewood Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 31154,
      badge: 'assets/imgs/england/leagueOne/blackburn.png',
      sponsor: 'BLANK.png',
      rival: 'Burnley',
      founded: 1875,
      opened: 1890,
      hashTag: '#Rovers',
      knownAs: 'Rovers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Blackpool',
      stadium: 'Bloomfield Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 16220,
      badge: 'assets/imgs/england/leagueOne/blackpool.png',
      sponsor: 'BLANK.png',
      rival: 'Preston North End',
      founded: 1887,
      opened: 1899,
      hashTag: '#BlackpoolFC',
      knownAs: 'The Seasiders',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bradford City',
      stadium: 'Valley Parade',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 25136,
      badge: 'assets/imgs/england/leagueOne/bradford.png',
      sponsor: 'BLANK.png',
      rival: 'Hull City',
      founded: 1903,
      opened: 1903,
      hashTag: '#BCAFC',
      knownAs: 'The Bantams',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bristol Rovers',
      stadium: 'Memorial Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 12011,
      badge: 'assets/imgs/england/leagueOne/bristolRovers.png',
      sponsor: 'BLANK.png',
      rival: 'Bristol City',
      founded: 1883,
      opened: 1921,
      hashTag: '#BristolRovers',
      knownAs: 'The Pirates',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Bury',
      stadium: 'Gigg Lane',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 11840,
      badge: 'assets/imgs/england/leagueOne/bury.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'Bolton Wanderers',
      founded: 1885,
      opened: 1885,
      hashTag: '#BuryFC',
      knownAs: 'The Shakers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Charlton Athletic',
      stadium: 'The Valley',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 27111,
      badge: 'assets/imgs/england/leagueOne/charlton.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'Crystal Palace',
      founded: 1905,
      opened: 1919,
      hashTag: '#CAFC',
      knownAs: 'The Addicks',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Doncaster Rovers',
      stadium: 'Keepmoat Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 15231,
      badge: 'assets/imgs/england/leagueOne/doncaster.png',
      sponsor: 'BLANK.png',
      rival: 'Rotherham United',
      founded: 1879,
      opened: 2007,
      hashTag: '#DRFC',
      knownAs: 'Rovers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Rotherham United',
      stadium: 'AESSEAL New York Stadiumn',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 12021,
      badge: 'assets/imgs/england/leagueOne/fleetwood.png',
      sponsor: 'aesseal.png',
      rival: 'Doncaster Rovers',
      founded: 1925,
      opened: 2012,
      hashTag: '#RUFC',
      knownAs: 'The Millers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Fleetwood Town',
      stadium: 'Highbury Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 5094,
      badge: 'assets/imgs/england/leagueOne/gillingham.png',
      sponsor: 'BLANK.png',
      rival: 'Morecombe',
      founded: 1908,
      opened: 1939,
      hashTag: '#CodArmy',
      knownAs: 'The Fishermen',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Gillingham',
      stadium: 'Priestfield Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 11582,
      badge: 'assets/imgs/england/leagueOne/miltonKeynes.png',
      sponsor: 'BLANK.png',
      rival: 'Millwall',
      founded: 1893,
      opened: 1893,
      hashTag: '#GillinghamFC',
      knownAs: 'The Gills',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Milton Keynes Dons',
      stadium: 'Stadium mk',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 22000,
      badge: 'assets/imgs/england/leagueOne/northampton.png',
      sponsor: 'BLANK.png',
      rival: 'AFC Wimbledon',
      founded: 2004,
      opened: 2008,
      hashTag: '#MKDons',
      knownAs: 'The Dons',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Northampton Town',
      stadium: 'Sixfields Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 7653,
      badge: 'assets/imgs/england/leagueOne/oldham.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'Peterborough United',
      founded: 1897,
      opened: 1994,
      hashTag: '#NTFC',
      knownAs: 'The Cobblers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Oldham Athletic',
      stadium: 'Boundary Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10638,
      badge: 'assets/imgs/england/leagueOne/oxford.png',
      sponsor: 'BLANK.png',
      rival: 'Rochdale',
      founded: 1895,
      opened: 1906,
      hashTag: '#OAFC',
      knownAs: 'The Latics',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Oxford United',
      stadium: 'Kassam Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 12500,
      badge: 'assets/imgs/england/leagueOne/peterborough.png',
      sponsor: 'BLANK.png',
      rival: 'Swindon Town',
      founded: 1893,
      opened: 2001,
      hashTag: '#OUFC',
      knownAs: 'The U s',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Peterborough United',
      stadium: 'London Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 15315,
      badge: 'assets/imgs/england/leagueOne/plymouth.png',
      sponsor: 'BLANK.png',
      rival: 'Cambridge United',
      founded: 1934,
      opened: 1934,
      hashTag: '#Posh',
      knownAs: 'The Posh',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Plymouth Argyle',
      stadium: 'Home Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 16388,
      badge: 'assets/imgs/england/leagueOne/portsmouth.png',
      sponsor: 'BLANK.png',
      rival: 'Exeter City',
      founded: 1886,
      opened: 1901,
      hashTag: '#PAFC',
      knownAs: 'The Pilgrims',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Portsmouth',
      stadium: 'Fratton Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 21100,
      badge: 'assets/imgs/england/leagueOne/rochdale.png',
      sponsor: 'BLANK.png',
      rival: 'Southampton',
      founded: 1898,
      opened: 1898,
      hashTag: '#Pompey',
      knownAs: 'Pompey',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Rochdale',
      stadium: 'Spotland Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10249,
      badge: 'assets/imgs/england/leagueOne/rotherhame.png',
      sponsor: 'BLANK.png',
      rival: 'Bury',
      founded: 1907,
      opened: 1920,
      hashTag: '#RochdaleFC',
      knownAs: 'The Dale',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Scunthorpe United',
      stadium: 'Glanford Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 9088,
      badge: 'assets/imgs/england/leagueOne/scunthorpe.png',
      sponsor: 'BLANK.png',
      rival: 'Grimsby Town',
      founded: 1899,
      opened: 1988,
      hashTag: '#Iron',
      knownAs: 'The Iron',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Shrewsbury Town',
      stadium: 'New Meadow',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 9875,
      badge: 'assets/imgs/england/leagueOne/shrewsbury.png',
      sponsor: 'BLANK.png',
      rival: 'Walsall',
      founded: 1886,
      opened: 2007,
      hashTag: '#Shrews',
      knownAs: 'The Shrews',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Southend United',
      stadium: 'Roots Hall',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 12392,
      badge: 'assets/imgs/england/leagueOne/southend.png',
      sponsor: 'BLANK.png',
      rival: 'Colchester United',
      founded: 1906,
      opened: 1955,
      hashTag: '#Southend',
      knownAs: 'The Shrimpers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Walsall',
      stadium: 'Bescot Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 11300,
      badge: 'assets/imgs/england/leagueOne/walsall.png',
      sponsor: 'BLANK.png',
      rival: 'Shrewsbury Town',
      founded: 1888,
      opened: 1990,
      hashTag: '#WalsallFC',
      knownAs: 'The Saddlers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Wigan Athletic',
      stadium: 'DW Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 25138,
      badge: 'assets/imgs/england/leagueOne/wigan.png',
      sponsor: 'DW.png',
      rival: 'Bolton Wanderers',
      founded: 1932,
      opened: 1999,
      hashTag: '#WAFC',
      knownAs: 'The Lactics',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }]
  }
},
{
  league: {
    id: 'League Two',
    country: 'England',
    teams: [{
      name: 'Accrington Stanley',
      stadium: 'Crown Ground',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 5057,
      badge: 'assets/imgs/england/leagueTwo/accrington.png',
      sponsor: 'BLANK.png',
      rival: 'Morecambe',
      founded: 1968,
      opened: 1968,
      hashTag: '#ASFC',
      knownAs: 'Stanley',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Barnet',
      stadium: 'The Hive Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 5233,
      badge: 'assets/imgs/england/leagueTwo/barnet.png',
      sponsor: 'BLANK.png',
      rival: 'Enfield Town',
      founded: 1888,
      opened: 2013,
      hashTag: '#BarnetFC',
      knownAs: 'The Bees',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Cambridge United',
      stadium: 'Abbey Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10847,
      badge: 'assets/imgs/england/leagueTwo/cambridge.png',
      sponsor: 'BLANK.png',
      rival: 'Peterborough United',
      founded: 1912,
      opened: 1931,
      hashTag: '#CUFC',
      knownAs: 'The U\'s',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Carlisle United',
      stadium: 'Brunton Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 18202,
      badge: 'assets/imgs/england/leagueTwo/carlisle.png',
      sponsor: 'SPONSORNAME.png',
      rival: ' Middlesbrough',
      founded: 1887,
      opened: 1927,
      hashTag: '#CUFC',
      knownAs: 'The Cumbrians',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Cheltenham Town',
      stadium: 'Whaddon Road ',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 7066,
      badge: 'assets/imgs/england/leagueTwo/cheltenham.png',
      sponsor: 'SPONSORNAME.png',
      rival: ' Forest Green Rovers ',
      founded: 1904,
      opened: 1909,
      hashTag: '#CTFC',
      knownAs: 'The Robins',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Chesterfield',
      stadium: 'Proact Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10400,
      badge: 'assets/imgs/england/leagueTwo/chesterfield.png',
      sponsor: 'B2net.png',
      rival: 'Mansfield',
      founded: 1919,
      opened: 2010,
      hashTag: '#ChesterfieldFC',
      knownAs: 'The Spireites',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Colchester United',
      stadium: 'Weston Homes Community Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10084,
      badge: 'assets/imgs/england/leagueTwo/colchester.png',
      sponsor: 'WestonHomes.png',
      rival: 'Southend United',
      founded: 1937,
      opened: 2008,
      hashTag: '#ColU',
      knownAs: 'The U\'s',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Coventry City',
      stadium: 'Ricoh Arena',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 32609,
      badge: 'assets/imgs/england/leagueTwo/coventry.png',
      sponsor: 'Ricoh.png',
      rival: 'Leicester City',
      founded: 1883,
      opened: 2005,
      hashTag: '#SkyBlues',
      knownAs: 'The Sky Blues',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Crawley Town',
      stadium: 'Broadfield Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 5996,
      badge: 'assets/imgs/england/leagueTwo/crawley.png',
      sponsor: 'BLANK.png',
      rival: 'AFC Wimbledon',
      founded: 1896,
      opened: 1997,
      hashTag: '#COYR',
      knownAs: 'Red Devils',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Crewe Alexandra',
      stadium: 'Gresty Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10153,
      badge: 'assets/imgs/england/leagueTwo/crewe.png',
      sponsor: 'BLANK.png',
      rival: 'Port Vale',
      founded: 1877,
      opened: 1898,
      hashTag: '#CreweAlex',
      knownAs: 'The Railway Men',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Exeter City',
      stadium: 'St James Park, Exeter',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 8541,
      badge: 'assets/imgs/england/leagueTwo/exeter.png',
      sponsor: 'BLANK.png',
      rival: 'Plymouth Argyle',
      founded: 1901,
      opened: 1904,
      hashTag: '#ECFC',
      knownAs: 'The Grecians',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Forest Green Rovers',
      stadium: 'The New Lawn',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 5147,
      badge: 'assets/imgs/england/leagueTwo/forestGreen.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'RIVALNAME',
      founded: 1889,
      opened: 2006,
      hashTag: '#WeAreFGR',
      knownAs: 'The Green',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Grimsby Town',
      stadium: 'Blundell Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 9546,
      badge: 'assets/imgs/england/leagueTwo/grimsby.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'RIVALNAME',
      founded: 1878,
      opened: 1899,
      hashTag: '#GTFC',
      knownAs: 'The Mariners',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Lincoln City',
      stadium: 'Sincil Bank',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10120,
      badge: 'assets/imgs/england/leagueTwo/lincoln.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'RIVALNAME',
      founded: 1884,
      opened: 1895,
      hashTag: '#Imps',
      knownAs: 'The Imps',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Luton Town',
      stadium: 'Kenilworth Road',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10226,
      badge: 'assets/imgs/england/leagueTwo/luton.png',
      sponsor: 'BLANK.png',
      rival: 'Watford',
      founded: 1885,
      opened: 1905,
      hashTag: '#LTFC',
      knownAs: 'The Hatters',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Mansfield Town',
      stadium: 'Field Mill',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 9186,
      badge: 'assets/imgs/england/leagueTwo/mansfield.png',
      sponsor: 'BLANK.png',
      rival: 'Chesterfield',
      founded: 1897,
      opened: 1861,
      hashTag: '#MTFC',
      knownAs: 'The Stags',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Morecambe',
      stadium: 'Globe Arena',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 6476,
      badge: 'assets/imgs/england/leagueTwo/morecambe.png',
      sponsor: 'BLANK.png',
      rival: 'Accrington Stanley',
      founded: 1920,
      opened: 2010,
      hashTag: '#MorcambeFC',
      knownAs: 'The Shrimps',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Newport County',
      stadium: 'Rodney Parade',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 7850,
      badge: 'assets/imgs/england/leagueTwo/newport.png',
      sponsor: 'BLANK.png',
      rival: 'Cardiff City',
      founded: 1912,
      opened: 1877,
      hashTag: '#SupportThePort',
      knownAs: 'The Exiles',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Notts County',
      stadium: 'Meadow Lane',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 20229,
      badge: 'assets/imgs/england/leagueTwo/notts.png',
      sponsor: 'SPONSORNAME.png',
      rival: 'Nottingham Forest',
      founded: 1862,
      opened: 1910,
      hashTag: 'Notts',
      knownAs: 'The Magpies',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Port Vale',
      stadium: 'Vale Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 19052,
      badge: 'assets/imgs/england/leagueTwo/portVale.png',
      sponsor: 'BLANK.png',
      rival: 'Stoke City',
      founded: 1876,
      opened: 1950,
      hashTag: '#PVFC',
      knownAs: 'The Valiants',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Stevenage Borough',
      stadium: 'The Lamex Stadium',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 6722,
      badge: 'assets/imgs/england/leagueTwo/stevenage.png',
      sponsor: 'BLANK.png',
      rival: 'Barnet',
      founded: 1976,
      opened: 1980,
      hashTag: '#StevenageFC',
      knownAs: 'Boro',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Swindon Town',
      stadium: 'The County Ground',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 15728,
      badge: 'assets/imgs/england/leagueTwo/swindon.png',
      sponsor: 'BLANK.png',
      rival: 'Oxford United',
      founded: 1879,
      opened: 1896,
      hashTag: '#STFC',
      knownAs: 'The Robins',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Wycombe Wanderers',
      stadium: 'Adams Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 10284,
      badge: 'assets/imgs/england/leagueTwo/wycombe.png',
      sponsor: 'BLANK.png',
      rival: 'Oxford United',
      founded: 1887,
      opened: 1991,
      hashTag: '#ChairBoys',
      knownAs: 'The Chairboys',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }, {
      name: 'Yeovil Town',
      stadium: 'Huish Park',
      stadiumImage: 'assets/imgs/england/premierLeague/old-trafford.jpg',
      capacity: 9665,
      badge: 'assets/imgs/england/leagueTwo/yeovil.png',
      sponsor: 'BLANK.png',
      rival: 'Bristol Rovers',
      founded: 1895,
      opened: 1990,
      hashTag: '#YTFC',
      knownAs: 'The Glovers',
      address: 'Sir Matt Busby Way, Stretford, Manchester M16 0RA'
    }]
  }
}
]

@Component({
  selector: 'selectclub',
  templateUrl: 'SelectClub.html'
})
export class SelectClub {
  premierLeagueTeams = [];
  championshipTeams = [];
  leagueOneTeams = [];
  leagueTwoTeams = [];
  league: string = "Premier League";
  constructor(public navCtrl: NavController, public navParams: NavParams) {
    clubList.forEach(i => {
      if (i.league.id === 'Premier League') {
        i.league.teams.forEach(team => {
          this.premierLeagueTeams.push(team);
        });
      }
      if (i.league.id === 'Championship') {
        i.league.teams.forEach(team => {
          this.championshipTeams.push(team);
        });
      }
      if (i.league.id === 'League One') {
        i.league.teams.forEach(team => {
          this.leagueOneTeams.push(team);
        });
      }
      if (i.league.id === 'League Two') {
        i.league.teams.forEach(team => {
          this.leagueTwoTeams.push(team);
        });
      }
    });
  }

  itemTapped(event, club) {
    this.navCtrl.push(ClubDetails, {
      club: club
    });
  }
}
